eureka:
  instance:
    hostname: localhost
    preferIpAddress: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: authentication-service
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
