eureka:
  instance:
    hostname: authentication-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: authentication-service
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/rateyourmusic
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/rateyourmusic
