spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rateyourmisic-keycloak-dev
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/rateyourmisic-keycloak-dev

eureka:
  instance:
    preferIpAddress: true