eureka:
  instance:
    hostname: discovery-service
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka/
      
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
