eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
      
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
