eureka:
  instance:
    hostname: domain-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:      
  datasource:
    url: jdbc:postgresql://domain_service_db:5432/domain_service_db
    username: ds_admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  liquibase:
    change-log: classpath:db_changelog_master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/rateyourmusic
