eureka:
  instance:
    hostname: domain-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: authentication-service
            client-secret: DZe7Ga0uxblLIGwtc0GhChAAsKcM0Tlh
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/auth/realms/rateyourmusic
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/rateyourmusic
  datasourse:
    url: jdbc:postgresql://postgres:5432/keycloak
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://localhost:8083/auth/realms/auth-server
#           jwk-set-uri: http://localhost:8083/auth/realms/auth-server/protocol/openid-connect/certs