eureka:
  instance:
    hostname: gateway-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        # - id: authentication-service
        #   uri: http://authentication-service:8088/
        #   predicates:
        #     - Path=/authentication-service/**
        #   filters:
        #     - RewritePath=/authentication-service/(?<path>.*), /$\{path}
          - id: authentication-service
            uri: http://keycloak:8080/
            predicates:
              - Path=/authentication-service/**
            filters:
              - RewritePath=/authentication-service/(?<path>.*), /$\{path}

        - id: temp-service
          uri: http://temp-service:8011/
          predicates:
            - Path=/temp-service/**
          filters:
            - RewritePath=/temp-service/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
