eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
   main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

        # - id: domain-service
        #   uri: lb://domain-service
        #   predicates:
        #     - Path=/domain-service/**
        #   filters:
        #     - RewritePath=/domain-service/(?<path>.*), /$\{path}
        # 
        # - id: file-service
        #   uri: lb://file-service
        #   predicates:
        #     - Path=/file-service/**
        #   filters:
        #     - RewritePath=/file-service/(?<path>.*), /$\{path}
        #
        # - id: notification-service
        #   uri: lb://notification-service
        #   predicates:
        #     - Path=/notification-service/**
        #   filters:
        #     - RewritePath=/notification-service/(?<path>.*), /$\{path}
