eureka:
  instance:
    hostname: gateway-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: domain-service
          uri: http://domain-service:8011/
          predicates:
            - Path=/domain-service/**
          filters:
            - RewritePath=/domain-service/(?<path>.*), /$\{path}   
        - id: keycloak
          uri: http://keycloak:8080/
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/keycloak/auth/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
