management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  # instance:
  #   preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
   main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: domain-service
          uri: lb://benefit-service
          predicates:
            - Path=/benefit-service/**
          filters:
            - RewritePath=/benefit-service/(?<path>.*), /$\{path}

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
          filters:
            - RewritePath=/file-service/(?<path>.*), /$\{path}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}
