eureka:
  instance:
    hostname: gateway-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://authentication-service:8080
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
